### ISSUE TITLE
Doc: more information on what is difference vs official node client

### ISSUE THREAD

**Issue by hpvd** [ayeo-flex-org/pulsar-flex#84]
**Is your feature request related to a problem? Please describe.**
Just found your interesting looking pulsar client!
You are writing in About:
- Pulsar Flex is a _modern_ Apache Pulsar client for Node.js, developed to be independent of C++.
- It was developed because the dependency in the official c++ external libraries _does not fit some use cases_.

**Describe the solution you'd like**
Would be pretty handy to give some more information on what is better/more modern and what use cases you have in mind ... in comparison to official node client.

Maybe one could also
- link directly to the repository of the official pulsar node client https://github.com/apache/pulsar-client-node and
- refer to missing feature in the official client https://docs.google.com/spreadsheets/d/1YHYTkIXR8-Ql103u-IMI18TXLlGStK8uJjDsOOA0T20/edit#gid=1784579914

**Additional context**
btw: to connect communities, I opened an issue to link in Doc directly to interesting 3rd party clients like pulsar-flex
https://github.com/apache/pulsar/issues/17113

**Comment by galrose** [comment]
Hey, sorry for the late reply.
I'm trying to understand what info you want to add. 
The  difference isn't features but different operating systems or other issues that make using C++ difficult.
The docs do have a link to this repository: https://pulsar.apache.org/docs/next/client-libraries
